# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

# file-version: 1.0

version: 2

updates:
  - package-ecosystem: "composer"

    directory: "/"

    schedule:
      interval: "cron"
      cronjob: "0 4 14 * *"
      timezone: "Europe/Berlin"

    cooldown:
      default-days: 7

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    versioning-strategy: "increase"

    commit-message:
      include: "scope"
      prefix: "composer (master)"

    ignore:
      - dependency-name: "laminas/laminas-servicemanager"
      - dependency-name: "psr/container"

    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "cron"
      cronjob: "0 4 14 * *"
      timezone: "Europe/Berlin"

    cooldown:
      default-days: 7

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    commit-message:
      prefix: "github-actions (master)"

    ignore:
      - dependency-name: "mimmi20/ci"
      - dependency-name: "release-drafter/release-drafter"

    rebase-strategy: "disabled"

  - package-ecosystem: "composer"

    directory: "/"

    schedule:
      interval: "cron"
      cronjob: "0 4 14 * *"
      timezone: "Europe/Berlin"

    cooldown:
      default-days: 7

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    versioning-strategy: "increase"

    target-branch: "5.x"

    commit-message:
      include: "scope"
      prefix: "composer (5.x)"

    ignore:
      - dependency-name: "laminas/laminas-servicemanager"
      - dependency-name: "psr/container"

    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "cron"
      cronjob: "0 4 14 * *"
      timezone: "Europe/Berlin"

    cooldown:
      default-days: 7

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "5.x"

    commit-message:
      prefix: "github-actions (5.x)"

    ignore:
      - dependency-name: "mimmi20/ci"
      - dependency-name: "release-drafter/release-drafter"

    rebase-strategy: "disabled"
